name: Solaris Core
main: com.solaris.core.Core
version: 0.0.1
author: PossiblyShea
api-version: 1.8
commands:
  heal:
    description: Heals the player
    usage: /<command>
    aliases: healme
# ( ◕◡◕)っ ♡
  feed:
    description: Feeds the player
    usage: /<command>
    aliases: feedme
  fly:
    description: Makes the player fly
    usage: /<command>